import Foundation

/// Builds a self-contained Markdown reference an agent can use to design presets for the amp.
public struct MarkdownExporter {
    public var catalog: Catalog
    public var ampPresets: [Preset]
    public var info: AmpInfo?
    public var includeFactoryLibrary = true

    public init(catalog: Catalog, ampPresets: [Preset], info: AmpInfo?) {
        self.catalog = catalog
        self.ampPresets = ampPresets
        self.info = info
    }

    public func render(date: Date = Date()) -> String {
        var md = ""
        let model = info?.modelName ?? "Mustang LT"
        md += "# \(model): preset reference for agents\n\n"
        let stamp = ISO8601DateFormatter.string(from: date, timeZone: .current, formatOptions: [.withFullDate])
        md += "Generated by ToneLT on \(stamp)"
        if let info { md += " from a \(info.modelName) (firmware \(info.firmware), product id `\(info.productId)`)" }
        md += ". Amp/effect definitions come from \(catalog.source).\n\n"

        md += """
        ## How to make a preset

        Use `ltctl` (the command-line tool that ships inside ToneLT.app, also available for Windows \
        and Linux). It converts the knob values below into what the amp stores and checks everything:

        ```sh
        ltctl new "Brighton Rock" amp=ac30 amp.gain=7 amp.treble=6.5 stomp=overdrive stomp.gain=2.5 \\
          delay=delay delay.time=800ms delay.feedback=5 reverb=plate reverb.level=3 -o brighton.preset
        ltctl show brighton.preset                # check it
        ltctl audition brighton.preset            # hear it without saving
        ltctl push brighton.preset --slot empty   # store it in the first empty slot
        ltctl set 35 amp.gain=7 delay=none        # edit a stored preset (backed up first)
        ```

        - Keys: `name`, a position (`stomp mod amp delay reverb`) to choose its unit, or \
        `<position>.<parameter>`.
        - Units: the amp's menu name (`"60S UK CLN"`), the FenderId (`DUBS_Ac30Tb`) or any unique part \
        (`ac30`); `none` empties a position (not the amp). Choosing a unit resets its parameters, so \
        set parameters after it.
        - Values: the **display** values in the tables below (knobs 1–10, ms, %…), list options by \
        stored or displayed name, `on`/`off`, or `raw:<value>` for an exact stored value.
        - Names: two lines of 8 characters (letters, digits, spaces).
        - `ltctl guide` explains the CLI; add `--json` to any command for machine output.

        Rules the amp enforces (ltctl checks them):

        - The chain is always `stomp → mod → amp → delay → reverb`; each position takes only the \
        units listed for it below.
        - The amp never stores `"bypass": true`; leave an effect out with `<position>=none`.
        - A preset must stay under 4000 bytes when sent (every preset here is ~2 KB).


        """

        md += "## Preset template\n\n"
        md += "What `.preset` files contain (the amp's own EMPTY template); you normally don't write this by hand.\n\n"
        md += "```json\n\(PresetJSON.prettyPrinted(catalog.emptyPresetJSON))\n```\n\n"
        if let example = ampPresets.first(where: { !$0.isEmptySlot }) {
            md += "A real preset from this amp (slot \(example.slot ?? 0), “\(example.displayName)”):\n\n"
            md += "```json\n\(PresetJSON.prettyPrinted(example.json))\n```\n\n"
        }

        md += renderAvailableUnits()
        md += renderKnobValues()
        md += renderUnitReference()
        md += renderAmpPresets()
        if includeFactoryLibrary { md += renderFactoryLibrary() }
        return md
    }

    private func renderAvailableUnits() -> String {
        var md = "## Available units\n\n"
        md += "Menu names are what the amp shows on its display.\n\n"
        for slot in ChainSlot.allCases {
            md += "### `\(slot.rawValue)` (\(slot.section))\n\n| FenderId | Amp menu name | Fender Tone name |\n|---|---|---|\n"
            for option in catalog.options[slot] ?? [] {
                let name = catalog.unit(option.fenderId)?.displayName ?? ""
                md += "| `\(option.fenderId)` | \(option.menuName) | \(name) |\n"
            }
            md += "\n"
        }
        return md
    }

    private func renderKnobValues() -> String {
        var md = """
        ## Knob values

        Presets store **raw** values. Fender Tone and the amp show a **display** value (usually 1–10). \
        For a continuous parameter with raw range `min…max`, taper `T` and display range `dmin…dmax` \
        with display taper `R`:

        - raw → display: `display = dmin + (dmax - dmin) * R((raw - min) / (max - min))`
        - display → raw: `raw = min + (max - min) * R⁻¹((display - dmin) / (dmax - dmin))`

        The tapers used here, for position `x` in 0…1 (`E(k,x) = (k^x − 1)/(k − 1)`, \
        `L(k,x) = ln(x(k − 1) + 1)/ln k`):

        | Taper | Curve |
        |---|---|

        """
        var names = Set<String>()
        for unit in catalog.units.values {
            for p in unit.params {
                if let n = p.taperName { names.insert(n) }
                if let n = p.remapTaperName { names.insert(n) }
            }
        }
        for name in names.sorted() {
            md += "| `\(name)` | \(describe(Taper(name: name))) |\n"
        }
        md += "\nIn every definition here the display taper is the inverse of the raw taper, so display values "
        md += "are linear in knob rotation; the tables below list raw values at each whole display step.\n\n"
        return md
    }

    private func describe(_ taper: Taper) -> String {
        func k(_ v: Double) -> String { String(format: "%g", v) }
        switch taper {
        case .linear: return "linear, `x`"
        case .exponential(let v): return "`E(\(k(v)), x)`"
        case .logarithmic(let v): return "`L(\(k(v)), x)`"
        case .sCurveExponential(let v): return "S-curve of `E(\(k(v)))`: `x<0.5 ? (1 − E(1 − 2x))/2 : (1 + E(2x − 1))/2`"
        case .sCurveLogarithmic(let v): return "S-curve of `L(\(k(v)))`: `x<0.5 ? (1 − L(1 − 2x))/2 : (1 + L(2x − 1))/2`"
        }
    }

    private func renderUnitReference() -> String {
        var md = "## Unit reference\n\n"
        md += "“Panel” marks parameters Fender Tone shows for the Mustang LT. The others are stored in every preset and "
        md += "the amp's DSP uses them (cabinet, noise gate, sag, bias…); their options come from Fender's full editor definitions.\n\n"
        let order = ChainSlot.allCases.flatMap { slot in (catalog.options[slot] ?? []).map { ($0.fenderId, slot) } }
        var seen = Set<String>()
        for (fenderId, slot) in order where !seen.contains(fenderId) && fenderId != "DUBS_Passthru" {
            seen.insert(fenderId)
            guard let unit = catalog.unit(fenderId) else { continue }
            md += "### `\(fenderId)`: \(unit.displayName) (\(slot.rawValue))\n\n"
            var notes: [String] = []
            if unit.hasBypass { notes.append("has `bypass` on/off") }
            if unit.hasTap, let tap = unit.tapParameter { notes.append("tap tempo sets `\(tap)`") }
            if !notes.isEmpty { md += notes.joined(separator: "; ").prefix(1).uppercased() + notes.joined(separator: "; ").dropFirst() + ".\n\n" }
            md += "Defaults: `\(defaultsJSON(unit))`\n\n"
            md += "| Parameter | Name | Panel | Type | Raw values | Display | Default |\n|---|---|---|---|---|---|---|\n"
            for p in unit.params {
                md += "| `\(p.id)` | \(p.displayName) | \(p.onLTPanel ? "yes" : "") | \(p.kind.rawValue) | \(rawDescription(p)) | \(displayDescription(p)) | \(unit.defaults[p.id].map { p.displayString(for: $0) + " (`\($0)`)" } ?? "") |\n"
            }
            let extra = unit.defaults.keys.filter { unit.param($0) == nil && $0 != "bypass" }.sorted()
            for key in extra {
                md += "| `\(key)` | | | fixed | keep `\(unit.defaults[key]!)` | | |\n"
            }
            md += "\n"
            let steps = unit.params.filter { $0.kind == .continuous && $0.remap?.min != nil && ($0.taperName ?? "t50") != "t50" }
            for p in steps {
                guard let dmin = p.remap?.min, let dmax = p.remap?.max else { continue }
                let lo = Int(ceil(Swift.min(dmin, dmax))), hi = Int(floor(Swift.max(dmin, dmax)))
                guard hi > lo, hi - lo <= 20 else { continue }
                let row = (lo...hi).compactMap { d in p.rawValue(display: Double(d)).map { "\(d)→`\(formatNumber(($0 * 1e6).rounded() / 1e6))`" } }
                md += "`\(p.id)` raw value per display step: " + row.joined(separator: ", ") + "\n\n"
            }
        }
        return md
    }

    private func defaultsJSON(_ unit: DSPUnitSpec) -> String {
        unit.defaults.keys.sorted().map { "\"\($0)\": \(unit.defaults[$0]!)" }.joined(separator: ", ")
    }

    private func rawDescription(_ p: ParamSpec) -> String {
        switch p.kind {
        case .list:
            return p.listItems.map { "`\"\($0)\"`" }.joined(separator: ", ")
        case .listBool:
            return "`false` / `true`"
        case .continuous:
            guard let min = p.min, let max = p.max else { return "number" }
            var s = "\(formatNumber(min)) … \(formatNumber(max))"
            if let u = p.rawUnits, !u.isEmpty { s += " \(u)" }
            if let t = p.taperName, t != "t50" { s += ", taper `\(t)`" }
            return s
        }
    }

    private func displayDescription(_ p: ParamSpec) -> String {
        switch p.kind {
        case .list:
            return p.remap?.listItems.joined(separator: ", ") ?? ""
        case .listBool:
            return p.remap?.listItems.joined(separator: " / ") ?? "Off / On"
        case .continuous:
            guard let r = p.remap, let dmin = r.min, let dmax = r.max else { return "same as raw" }
            var s = "\(formatNumber(dmin)) … \(formatNumber(dmax))"
            if let u = p.displayUnits { s += " \(u)" }
            if let t = p.remapTaperName, t != "t50" { s += ", taper `\(t)`" }
            return s
        }
    }

    private func summary(_ preset: Preset) -> String {
        ChainSlot.allCases.compactMap { slot -> String? in
            guard let node = preset.node(slot), !node.isEmpty else { return nil }
            let unit = catalog.unit(node.fenderId)
            var text = "**\(slot.title)** \(catalog.menuName(node.fenderId) ?? unit?.displayName ?? node.fenderId)"
            if node.isBypassed { text += " (off)" }
            let knobs = (unit?.params ?? []).filter(\.onLTPanel).compactMap { p -> String? in
                node.params[p.id].map { "\(p.displayName.lowercased()) \(p.displayString(for: $0))" }
            }
            if !knobs.isEmpty { text += ": " + knobs.joined(separator: ", ") }
            return text
        }.joined(separator: "; ")
    }

    private func renderAmpPresets() -> String {
        guard !ampPresets.isEmpty else { return "" }
        var md = "## Presets currently on the amp\n\n"
        let used = ampPresets.filter { !$0.isEmptySlot }
        let empty = ampPresets.filter(\.isEmptySlot).compactMap(\.slot)
        md += "\(used.count) of \(ampPresets.count) slots are in use."
        if !empty.isEmpty { md += " Empty slots (safe to fill): \(ranges(empty))." }
        md += " Knob values are display values.\n\n| Slot | Name | Chain |\n|---|---|---|\n"
        for p in used {
            md += "| \(p.slot ?? 0) | \(p.displayName) (`\"\(p.rawName)\"`) | \(summary(p)) |\n"
        }
        md += "\n<details><summary>Full JSON of every preset on the amp</summary>\n\n"
        for p in used {
            md += "#### Slot \(p.slot ?? 0): \(p.displayName)\n\n```json\n\(p.json)\n```\n\n"
        }
        md += "</details>\n\n"
        return md
    }

    private func renderFactoryLibrary() -> String {
        guard !catalog.factoryPresets.isEmpty else { return "" }
        var md = "## Fender factory preset library\n\n"
        md += "The \(catalog.factoryPresets.count) presets Fender ships for the Mustang LT, useful as starting points. "
        md += "Import one with ToneLT's Factory Presets view, or copy its settings into a new preset.\n\n"
        md += "| Name | Chain |\n|---|---|\n"
        for p in catalog.factoryPresets {
            md += "| \(p.displayName) | \(summary(p)) |\n"
        }
        return md + "\n"
    }

    private func ranges(_ slots: [Int]) -> String {
        var parts: [String] = []
        var start = slots.first
        var prev = slots.first
        for s in slots.dropFirst() + [Int.max] {
            if let p = prev, s == p + 1 { prev = s; continue }
            if let a = start, let b = prev { parts.append(a == b ? "\(a)" : "\(a)–\(b)") }
            start = s
            prev = s
        }
        return parts.joined(separator: ", ")
    }
}
