// A self-contained Markdown reference an agent can use to design presets for the amp.

import { type Catalog, formatNumber, type ParamSpec, PASSTHRU, POSITIONS, type Position } from "./catalog";
import type { AmpInfo } from "./amp";
import type { Preset } from "./preset";
import { summarize } from "./summary";

const SECTION: Record<Position, string> = { stomp: "Pre FX", mod: "Pre FX", amp: "Amp", delay: "Post FX", reverb: "Post FX" };

function pretty(json: string): string {
  try {
    return JSON.stringify(JSON.parse(json), null, 2);
  } catch {
    return json;
  }
}

function describeTaper(name: string): string {
  const m = /^t(\d\d)(r?)(s?)(i?)$/.exec(name);
  if (!m || name === "t50") return "linear";
  return `${m[3] ? "S-curve " : ""}${m[2] ? "reversed " : ""}${m[4] ? "inverse " : ""}audio taper (${m[1]}% at half travel${m[2] ? ", mirrored" : ""})`;
}

export function renderMarkdown(catalog: Catalog, presets: Preset[], info: AmpInfo | undefined, options: { factory: boolean }): string {
  const lines: string[] = [];
  const add = (s = "") => lines.push(s);
  const model = info?.model ?? "Mustang LT";

  add(`# ${model}: preset reference for agents`);
  add();
  add(`Generated by ltctl on ${new Date().toISOString().slice(0, 10)}${info ? ` from a ${info.model} (firmware ${info.firmware}, product id \`${info.productId}\`)` : ""}. Amp/effect definitions come from ${catalog.source}.`);
  add();
  add(`## How to make a preset

Use \`ltctl\`; it converts the knob values below into what the amp stores and checks everything:

\`\`\`sh
ltctl new "Brighton Rock" amp=ac30 amp.gain=7 amp.treble=6.5 stomp=overdrive stomp.gain=2.5 \\
  delay=delay delay.time=800ms delay.feedback=5 reverb=plate reverb.level=3 -o brighton.preset
ltctl show brighton.preset            # check it
ltctl audition brighton.preset        # hear it on the amp without saving
ltctl push brighton.preset --slot empty   # store in the first empty slot
ltctl set 35 amp.gain=7 delay=none    # edit a stored preset in place (backed up first)
\`\`\`

- Keys: \`name\`, a position (\`stomp mod amp delay reverb\`) to choose its unit, or \`<position>.<parameter>\`.
- Units: the amp's menu name (\`"60S UK CLN"\`), the FenderId (\`DUBS_Ac30Tb\`) or any unique part (\`ac30\`). \`none\` empties a position (not allowed for \`amp\`). Choosing a unit resets its parameters to the unit's defaults, so set parameters after it.
- Values: the **display** values in the tables below (knobs 1–10, ms, %…), list options by stored or displayed name, \`on\`/\`off\` for switches, or \`raw:<value>\` for an exact stored value.
- Names: two lines of 8 characters (letters, digits, spaces), e.g. "Spread Wings" → \`"SPREAD  WINGS   "\`.
- \`ltctl units <unit>\` lists a unit's parameters; \`ltctl guide\` explains the CLI; add \`--json\` to any command for machine output.

Rules the amp enforces (ltctl checks them):

- The chain is always \`stomp → mod → amp → delay → reverb\`; each position takes only the units listed for it below.
- The amp never stores \`"bypass": true\`; leave an effect out with \`<position>=none\` (\`DUBS_Passthru\`).
- A preset must stay under 4000 bytes when sent (every preset here is ~2 KB).
`);

  add("## Preset JSON");
  add();
  add("What `.preset` files contain (the amp's own EMPTY template shown). You normally don't need to write this by hand.");
  add();
  add("```json");
  add(pretty(catalog.emptyPresetJSON));
  add("```");
  add();

  add("## Available units");
  add();
  add("Menu names are what the amp shows on its display.");
  add();
  for (const position of POSITIONS) {
    add(`### \`${position}\` (${SECTION[position]})`);
    add();
    add("| FenderId | Amp menu name | Fender Tone name |");
    add("|---|---|---|");
    for (const o of catalog.options.get(position) ?? []) add(`| \`${o.fenderId}\` | ${o.menuName} | ${catalog.unit(o.fenderId)?.displayName ?? ""} |`);
    add();
  }

  add("## Knob values");
  add();
  add("Presets store **raw** values; the amp and Fender Tone show **display** values (usually 1–10). ltctl converts for you. The formulas, for a raw range `min…max` and display range `dmin…dmax` with display taper `R`:");
  add();
  add("- raw → display: `display = dmin + (dmax − dmin) · R((raw − min) / (max − min))`");
  add("- display → raw: `raw = min + (max − min) · R⁻¹((display − dmin) / (dmax − dmin))`");
  add("- tapers use `E(k,x) = (k^x − 1)/(k − 1)` and its inverse `L(k,x) = ln(x(k − 1) + 1)/ln k`; knob rotation is linear in the display value.");
  add();

  add("## Unit reference");
  add();
  add("“Panel” marks parameters the Mustang LT shows; the others are stored in every preset and used by the DSP (cabinet, noise gate, sag, bias…).");
  add();
  const seen = new Set<string>();
  for (const position of POSITIONS) {
    for (const o of catalog.options.get(position) ?? []) {
      if (o.fenderId === PASSTHRU || seen.has(o.fenderId)) continue;
      seen.add(o.fenderId);
      const unit = catalog.unit(o.fenderId);
      if (!unit) continue;
      add(`### ${o.menuName}: \`${o.fenderId}\` (${position})`);
      add();
      add("| Parameter | Name | Panel | Display values | Default | Raw values |");
      add("|---|---|---|---|---|---|");
      for (const p of unit.params) {
        if (p.id === "bypassType") continue;
        const def = unit.defaults[p.id];
        add(`| \`${p.id}\` | ${p.displayName} | ${p.onPanel ? "yes" : ""} | ${displayRange(p)} | ${def === undefined ? "" : p.display(def)} | ${rawRange(p)} |`);
      }
      add();
      for (const p of unit.params) {
        if (p.kind !== "continuous" || !p.hasDisplayRange || (p.taperName ?? "t50") === "t50") continue;
        const lo = Math.ceil(Math.min(p.remap!.min!, p.remap!.max!));
        const hi = Math.floor(Math.max(p.remap!.min!, p.remap!.max!));
        if (hi <= lo || hi - lo > 20) continue;
        const steps: string[] = [];
        for (let d = lo; d <= hi; d++) steps.push(`${d}→\`${formatNumber(Math.round(p.rawValue(d)! * 1e6) / 1e6)}\``);
        add(`\`${p.id}\` is ${describeTaper(p.taperName!)}; raw per display step: ${steps.join(", ")}`);
        add();
      }
    }
  }

  if (presets.length) {
    const used = presets.filter((p) => !p.isEmptySlot);
    const empty = presets.filter((p) => p.isEmptySlot).map((p) => p.slot!);
    add("## Presets currently on the amp");
    add();
    add(`${used.length} of ${presets.length} slots are in use.${empty.length ? ` Empty slots (safe to fill): ${ranges(empty)}.` : ""} Values are display values; \`ltctl show <slot> --json\` gives full detail.`);
    add();
    add("| Slot | Name | Chain |");
    add("|---|---|---|");
    for (const p of used) add(`| ${p.slot} | ${p.displayName} | ${chainDetail(p, catalog)} |`);
    add();
  }

  if (options.factory) {
    add("## Fender factory preset library");
    add();
    add(`${catalog.factoryPresets.length} presets Fender ships for the Mustang LT, useful starting points for \`ltctl new --from "factory:<name>"\`.`);
    add();
    add("| Name | Chain |");
    add("|---|---|");
    for (const p of catalog.factoryPresets) add(`| ${p.displayName} | ${chainDetail(p, catalog)} |`);
    add();
  }
  return lines.join("\n");
}

function displayRange(p: ParamSpec): string {
  if (p.kind === "list") return p.listItems.map((item, i) => {
    const label = p.remap?.listItems[i];
    return label && label.toLowerCase() !== item.toLowerCase() ? `\`${item}\` (${label})` : `\`${item}\``;
  }).join(", ");
  if (p.kind === "listBool") return "`on` / `off`";
  if (p.hasDisplayRange) return `${formatNumber(p.remap!.min!)} … ${formatNumber(p.remap!.max!)}${p.displayUnits ? " " + p.displayUnits : ""}`;
  return `${formatNumber(p.min ?? 0)} … ${formatNumber(p.max ?? 1)}${p.rawUnits ? " " + p.rawUnits : ""}`;
}

function rawRange(p: ParamSpec): string {
  if (p.kind === "list") return "string";
  if (p.kind === "listBool") return "`true` / `false`";
  const units = p.rawUnits ? ` ${p.rawUnits}` : "";
  return `${formatNumber(p.min ?? 0)} … ${formatNumber(p.max ?? 1)}${units}${p.taperName && p.taperName !== "t50" ? `, \`${p.taperName}\`` : ""}`;
}

function chainDetail(p: Preset, catalog: Catalog): string {
  return summarize(p, catalog)
    .chain.filter((n) => !n.empty)
    .map((n) => `**${n.position}** ${n.unit}${n.params.filter((x) => x.panel).length ? ": " + n.params.filter((x) => x.panel).map((x) => `${x.name.toLowerCase()} ${x.display}`).join(", ") : ""}`)
    .join("; ");
}

function ranges(slots: number[]): string {
  const parts: string[] = [];
  let start = slots[0]!;
  let prev = start;
  for (const s of [...slots.slice(1), Infinity]) {
    if (s === prev + 1) {
      prev = s;
      continue;
    }
    parts.push(start === prev ? `${start}` : `${start}–${prev}`);
    start = prev = s;
  }
  return parts.join(", ");
}
